apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: red-result
spec:
  broker: default
  filter:
    sourceAndType:
      type: color.red
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: event-display

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: blue-result
spec:
  broker: default
  filter:
    sourceAndType:
      type: color.blue
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: event-display

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: green-result
spec:
  broker: default
  filter:
    sourceAndType:
      type: color.green
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: event-display
