apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: colors
spec:
  data: '{"color":"#FFF"}'
  schedule: '*/1 * * * *'
  sink:
    apiVersion: serving.knative.dev/v1beta1
    kind: Service
    name: input
